In [2]:
import numpy as np

In [3]:
# numpy 的基本属性
array = np.array([[1,2,3],
                 [4,5,6]])
print(array)
print("number of dimation:",array.ndim) # 维度
print("shape : ",array.shape)
print("size:",array.size)

[[1 2 3]
 [4 5 6]]
number of dimation: 2
shape :  (2, 3)
size: 6


In [46]:
# numpy 创建array
print("普通list",[1,2,3])
a = np.array([1,2,3],dtype=np.int64) # int32 float64 float32
print(a)
print(a.dtype)

b = np.array([[2,3,4],
              [5,6,7]])
print(b)

b = np.zeros((3,4))
print(b)
b = np.ones((3,4),dtype=np.int16)
print(b)
b = np.empty((3,4))
print(b)
b = np.arange(10,20,2) # 10到20步长2
print(b)
b = np.arange(12).reshape((3,4))
print(b)
b = np.linspace(1,10,5) # 生成线段等差数列
b_ = np.arange(1,10,5) # 10到20步长2
print(b)
print(b_)

普通list [1, 2, 3]
[1 2 3]
int64
[[2 3 4]
 [5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.    3.25  5.5   7.75 10.  ]
[1 6]


In [70]:
# numpy 基础的运算1
a = np.array([10,20,30,40])
b = np.arange(4)
print(a)
print(b)
print(a-b)
print(a+b)
print(a*b)
print(b**2) # 平方
print(np.sin(a)) # sin
print(np.cos(a)) # sin
print(b<3)

print("-----------------------------------------------")

a = np.array([[1,1],
              [0,1]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)
print(a*b)
print(np.dot(a,b))
print(a.dot(b))

print("-----------------------------------------------")

a = np.random.random((2,4)) # 0~1随机数字
print(a)
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.sum(a,axis=1)) # axis=1 列中求和


[10 20 30 40]
[0 1 2 3]
[10 19 28 37]
[10 21 32 43]
[  0  20  60 120]
[0 1 4 9]
[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ True  True  True False]
-----------------------------------------------
[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]
-----------------------------------------------
[[0.3057611  0.17444766 0.96816085 0.78052589]
 [0.47594969 0.36139405 0.02871035 0.78417328]]
3.8791228877622563
0.028710353773197972
0.9681608536458148
[2.22889551 1.65022738]


In [5]:
# numpy 基础的运算2
A = np.arange(14,2,-1).reshape((3,4))
print(A)
print(np.argmin(A)) # 最小值的索引
print(np.argmax(A)) # 最大值的索引
print(np.mean(A))
print(A.mean())
print(np.average(A))
print(np.median(A)) # 中位数
print("cumsum",np.cumsum(A)) # 累加
print("diff",np.diff(A)) # 累差
print("nonzero",np.nonzero(A)) # 累差
print("sort",np.sort(A)) # 累差
print(np.transpose(A))
print(A.T)
print((A.T).dot(A))
print(np.clip(A,5,9)) # 大于9的数字是9，小于5的是5
print(np.mean(A,axis=0))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
11
0
8.5
8.5
8.5
8.5
cumsum [ 14  27  39  50  60  69  77  84  90  95  99 102]
diff [[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
nonzero (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
sort [[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
[10.  9.  8.  7.]


In [167]:
#### numpy 索引
A = np.arange(3,15).reshape((3,4))
print(A)
print(A[2][1])
print(A[2,1])
print(A[2,:])
print(A[:,2])

for row in A:
    print(row)
print("----------------------------------------------")
for col in A.T:
    print(col)
    
print("----------------------------------------------")
print(A.flatten())

for item in A.flat:
    print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
12
12
[11 12 13 14]
[ 5  9 13]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
----------------------------------------------
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
----------------------------------------------
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [162]:
# array 合并
A = np.array([1,1,1])
B = np.array([2,2,2])

C = np.vstack((A,B))

print(A.shape)
print(C.shape)

C = np.hstack((A,B))
print("A.shape:\n",A.shape)
print("C.shape:\n",C.shape)
print("A.T:\n",A.T)
A = A[:,np.newaxis]
B = B[:,np.newaxis]
print("A:\n",A) # 在行上添加维度
print("B:\n",B) # 在列上添加维度
print("hstack\n",np.hstack((A,B)))

C = np.concatenate((A,B,B,A),axis=1)
print("concatenate:\n",C)

(3,)
(2, 3)
A.shape:
 (3,)
C.shape:
 (6,)
A.T:
 [1 1 1]
A:
 [[1]
 [1]
 [1]]
B:
 [[2]
 [2]
 [2]]
hstack
 [[1 2]
 [1 2]
 [1 2]]
concatenate:
 [[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [163]:
# array 分割
A = np.arange(12).reshape((3,4))
print(A)
print("split:\n",np.split(A,3,axis=0))
print("array_split:\n",np.array_split(A,3,axis=1))
print("vsplit:\n",np.vsplit(A,3))
print("hsplit:\n",np.hsplit(A,2))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
split:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
array_split:
 [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
vsplit:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
hsplit:
 [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [164]:
# array copy 和 deep copy
a = np.arange(4)
b=a
a[0]=8
print("a:",a)
print("b:",b)
print("b is a:",b is a)
b = a.copy()
a[1:3] = [44,55]
print("a:",a)
print("b:",b)

a: [8 1 2 3]
b: [8 1 2 3]
b is a: True
a: [ 8 44 55  3]
b: [8 1 2 3]
